services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  kanban_board:
    build:
      context: ./
      dockerfile: ./app/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    command: sh -c "sleep 5 && pnpx prisma migrate dev && pnpm run dev"

volumes:
  postgres_data:
  redis_data:
  node_modules:
